# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ae3a5ee66e65cb46815329f9eec1626c5a007e2618fee87963f258b25718505281bb854f020ee8c691c0ff2d4e6fabed70fc8eda16adf233fe2d4ddfb3bd6f4

test:
  secret_key_base: b0100b933dcb61006455ae003c49e3dcf4daeb743d32b79df8db70c1d0a3f0ecb727dc7a9c4ef286381c9b9b6c33a7fb100f20fc787e1e8ea48fdb5f7d2842eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
